"""добавил таблицу UserChat

Revision ID: 137cdd3b4f43
Revises: 8665b5e1d6ca
Create Date: 2022-06-21 15:00:00.633642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '137cdd3b4f43'
down_revision = '8665b5e1d6ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserChat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['Chats.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserChat')
    # ### end Alembic commands ###
