"""добавил поля прочитанного и изменённого сообщения

Revision ID: 8665b5e1d6ca
Revises: 
Create Date: 2022-06-21 14:53:07.186157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8665b5e1d6ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Messages', sa.Column('is_modified', sa.Boolean(), nullable=True))
    op.add_column('Messages', sa.Column('is_readed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Messages', 'is_readed')
    op.drop_column('Messages', 'is_modified')
    # ### end Alembic commands ###
